server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: ruta-auth
              uri: lb://AUTENTICACION
              predicates:
                - Path=/auth,/auth/**
            
            - id: ruta-catalogo
              uri: lb://CATALOGO
              predicates:
                - Path=/catalogo,/catalogo/**

            - id: ruta-editorial
              uri: lb://CATALOGO
              predicates:
                - Path=/editorial,/editorial/**

            - id: ruta-categoria
              uri: lb://CATALOGO
              predicates:
                - Path=/categoria,/categoria/**

            - id: ruta-listaDeseos
              uri: lb://LISTADESEOS
              predicates:
                - Path=/wishlist,/wishlist/**

            - id: ruta-listaDeseosDetalle
              uri: lb://LISTADESEOS
              predicates:
                - Path=/detalleWishlist,/detalleWishlist/**

            - id: ruta-carrito
              uri: lb://CARRITO
              predicates:
                - Path=/carrito,/carrito/**

            - id: ruta-carritoDetalle
              uri: lb://CARRITO
              predicates:
                - Path=/detalleCarrito,/detalleCarrito/**

            - id: ruta-pedidos
              uri: lb://PEDIDOS
              predicates:
                - Path=/pedidos,/pedidos/**

            - id: ruta-pagos
              uri: lb://PAGOS
              predicates:
                - Path=/pagos,/pagos/**

            - id: ruta-ventas
              uri: lb://VENTAS
              predicates:
                - Path=/ventas,/ventas/**

            - id: ruta-envio
              uri: lb://ENVIO
              predicates:
                - Path=/envio,/envio/**

            - id: ruta-entrega
              uri: lb://ENTREGA
              predicates:
                - Path=/entrega,/entrega/**

            - id: ruta-devoluciones
              uri: lb://DEVOLUCIONES
              predicates:
                - Path=/devoluciones,/devoluciones/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: false
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG